// Generates src/lib/motion/land.ts — land dots on a fibonacci sphere (base64 Int16 lat/lon ×100).
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
const topo = JSON.parse(readFileSync(new URL("../node_modules/world-atlas/land-110m.json", import.meta.url)));
const land = feature(topo, topo.objects.land);
const polys = land.features.flatMap((f) => f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates);
const inRing = (x, y, r) => { let c = false; for (let i = 0, j = r.length - 1; i < r.length; j = i++) { const [xi, yi] = r[i], [xj, yj] = r[j]; if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) c = !c; } return c; };
const onLand = (lon, lat) => polys.some((p) => inRing(lon, lat, p[0]) && !p.slice(1).some((h) => inRing(lon, lat, h)));
const N = 26000, out = [];
const ga = Math.PI * (3 - Math.sqrt(5));
for (let i = 0; i < N; i++) {
  const y = 1 - (i / (N - 1)) * 2, lat = Math.asin(y) * 180 / Math.PI;
  let lon = ((i * ga) * 180 / Math.PI) % 360; if (lon > 180) lon -= 360;
  if (lat < -58) continue; // skip Antarctica
  if (onLand(lon, lat)) out.push(Math.round(lat * 100), Math.round(lon * 100));
}
const b64 = Buffer.from(new Int16Array(out).buffer).toString("base64");
writeFileSync(new URL("../src/lib/motion/land.ts", import.meta.url), `// generated by scripts/gen-globe.mjs — ${out.length / 2} land points\nexport const LAND = "${b64}";\n`);
console.log(out.length / 2, "points", b64.length, "bytes");
